sudo: false
language: java
install: true
java:
  - 11
deploy:
  provider: pages
  github-token: 86264d500782b2cf7aace9550f7417a2d9d7e602
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  target-branch: master
  on:
    branch: master
