sudo: false
language: java
install: true
java:
  - 11
deploy:
  provider: pages
  github-token: 34963b957d785ea8ddefcc0ac5271a704d448301
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  target-branch: master
  on:
    branch: master
